


final dare=  const [
{'id': '1','que':"Let the group choose an item for you to brush your teeth with."},
{'id': '2','que':"Write your name on the floor with your tongue."},
{'id': '3','que':"Go outside and pick exactly 40 blades of grass with a pair of tweezers."},
{'id': '4','que':"Stick a Hot Cheeto in your nose and leave it there for 5 minutes."},
{'id': '5','que':"Open Facebook, go to the account of the first person you see, and like every post on their wall going back to a year."},
{'id': '6','que':"Eat a whole piece of paper."},
{'id': '7','que':"Lick a car tire."},
{'id': '8','que':"Open your front door and howl like a wolf for 30 seconds."},
{'id': '9','que':"Let the person to your right put duct tape on any part of your body they choose and rip it off."},
{'id': '10','que':"I dare you to tie your hands to your ankles for the rest of the game."},
{'id': '11','que':"Put a bunch of honey on your nose and coat it with flour"},
{'id': '12','que':"Dump a bunch of legos on the floor and walk over it with your bare feet."},
{'id': '13','que':"Eat a spoonful of mustard."},
{'id': '14','que':"Jump into a dumpster."},
{'id': '15','que':"Lift up the couch cushions, and if there is anything under it, you need to put it in your mouth for 10 seconds."},
{'id': '16','que':"Spin around 10 times and try to walk straight."},
{'id': '17','que':"Eat a raw egg."},
{'id': '18','que':"Write a letter to your doctor describing an embarrassing rash you have, and post it on Facebook."},
{'id': '19','que':"Cover your hair with shaving cream and leave it on until the end of the game."},
{'id': '20','que':"Let the group choose 3 random things from the refrigerator and mix it together. Then you have to eat it."},
{'id': '21','que':"Stand up and do jumping jacks until your next turn."},
{'id': '22','que':"Rub your armpits and then smell your fingers."},
{'id': '23','que':"Dig through the trash and name everything you find."},
{'id': '24','que':"Sniff another player’s armpit for 10 seconds."},
{'id': '25','que':"Give your phone to another player to send a text message to their contact of choice."},
{'id': '26','que':"Let the other players go through your phone for a minute."},
{'id': '27','que':"Allow someone to pour ice down your shirt and pants."},
{'id': '28','que':"Let another player throw flour in your face."},
{'id': '29','que':"Sing a song chosen by the group while eating spoonfuls of peanut butter."},
{'id': '30','que':"Close your eyes and let your friends put whatever food from the fridge they want in your mouth."},
{'id': '31','que':"One by one, make up a title for each players’ movie about their life."},
{'id': '32','que':"Let your friends pose you and stay like that until the next round."},
{'id': '33','que':"Let each player choose one word, then attempt to form a sentence with it and post it to Facebook."},
{'id': '34','que':"Empty your purse, backpack, or wallet and let everyone see what you have."},
{'id': '35','que':"Allow the person to your right to tickle you."},
{'id': '36','que':"Whoever’s name begins with an A in the group must call your parents and tell them what a bad friend you are to them."},
{'id': '37','que':"Let each person in the group slap you as hard as they can on your butt."},
{'id': '38','que':"Do your best impression of someone in the room and keep going until someone correctly guesses who it is."},
{'id': '39','que':"Eat a raw onion and do your best not to cry."},
{'id': '40','que':"Be blindfolded and let someone feed you something."},
{'id': '41','que':"Lick mayonnaise off of someone’s toe."},
{'id': '42','que':"Someone has to dip their finger in the trash can and you have to lick it."},
{'id': '43','que':"Go to the bathroom, and the person to your left has to be in there with you the whole time."},
{'id': '44','que':"Trade socks with the person to your right."},
{'id': '45','que':"Have the person to your right do 10 squats while you lie underneath them."},
{'id': '46','que':"Let a person in the group put a leash on you and walk you down the street."},
{'id': '47','que':"Hold hands with the person to you left for the rest of the game."},
{'id': '48','que':"Hand your phone to the person across from you and let them post whatever they want to your social media accounts."},
{'id': '49','que':"Smells someone else’s shoes"},
{'id': '50','que':"Take the socks off the person’s feet across from you and wear them like gloves until your next turn."},
{'id': '51','que':"Serenade the person next to you."},
{'id': '52','que':"Take a selfie with the person next to you, and post it on social media along with a deep and emotional paragraph about what they mean to you."},
{'id': '53','que':"Let the person across from you give you a wedgie."},
{'id': '54','que':"Dance aggressively until you run out of breath."},
{'id': '55','que':"Eat a single spaghetti like in Lady and the Tramp with the person to your left."},
{'id': '56','que':"Get a bar of soap from the bathroom and sell it to the group for 3 minutes."},
{'id': '57','que':"Go outside, and while skipping down the street, sing “Let it Go’ from Frozen."},
{'id': '58','que':"With your eyes closed, pick someone from your contact list and send them a text."},
{'id': '59','que':"Stand up and do your best impersonation of the person on your right."},
{'id': '60','que':"Go in the kitchen and rearrange everything in the food pantry in alphabetical order."},
{'id': '61','que':"Imagine the person to your left is your pet, talk to them as though you just got home."},
{'id': '62','que':"Imagine that you are a dog and act like it until your next turn."},
{'id': '63','que':"Describe what the sky looks like without using the words blue or white."},
{'id': '64','que':"Sing the chorus of your favorite song."},
{'id': '65','que':"Everytime someone chooses dare, walk across the floor like a crab and embrace them with a hug."},
{'id': '66','que':"Make up a song about the host of the party."},
{'id': '67','que':"Exchange shirts with the person to your left and wear it for the remainder of the game."},
{'id': '68','que':"Knock on the neighbor’s door and explain to them that your pet penguin got loose and ask if you can look for it in their backyard."},
{'id': '69','que':"Invent a new color for nail polish and describe the person who would be most likely to wear it."},
{'id': '70','que':"For the next 15 minutes, everything you say must be spoken in baby talk."},
{'id': '71','que':"Allow the person to your left to cut your hair however they see fit."},
{'id': '72','que':"Give 5 dollars to each player if you curse at any point during the game."},
{'id': '73','que':"Make a sandwich while blindfolded."},
{'id': '74','que':"Stick an egg in the microwave and attempt to juggle it for 30 seconds."},
{'id': '75','que':"Eat a spoonful of hot sauce."},
{'id': '76','que':"From now until your next turn, every time someone talks, interrupt by saying, “that’s a lie.”"},
{'id': '77','que':"You notice that the person sitting on your right has something on their face, spit on your finger and wipe it off for them."},
{'id': '78','que':"Get down on one knee and propose to the person on your left."},
{'id': '79','que':"Awkwardly smell someone else’s hair until they notice."},
{'id': '80','que':"Take the socks off the person’s feet across from you and wear them like gloves until your next turn."},
{'id': '81','que':"Open Facebook and “like” the first thing that pops up even if you disagree with it."},
{'id': '82','que':"Stand up and do your best impersonation of your mom."},
{'id': '83','que':"Go for a short walk outside and while walking, hold a conversation with yourself."},
{'id': '84','que':"Rearrange all the pictures in the room according to their size."},
{'id': '85','que':"Take off your shoe and clean your foot as though you are an animal."},
{'id': '86','que':"Stick your head in the toilet."},
{'id': '87','que':"Put makeup on the person sitting the farthest away from you."},
{'id': '88','que':"Do your best impersonation of someone else in the room and keep going until someone else guesses who you are."},
{'id': '89','que':"Call a realtor and show genuine interest in a random house for several minutes."},
{'id': '90','que':"For the next 10 minutes, when someone speaks, put your ear up close to them and act as though you can’t hear what they are saying."},
{'id': '91','que':"Stand up and do jumping jacks until your next turn."},
{'id': '92','que':"For the rest of the game, you must cluck like a chicken at the beginning and end of everything you say."},
{'id': '93','que':"Be silent and say nothing from now until your next turn."},
{'id': '94','que':"While blindfolded, you must eat something that the person to your left chooses to feed you."},
{'id': '95','que':"Tie your shoe strings together with another person and walk together to the end of the driveway and back."},
{'id': '96','que':"Stand in the backyard and yell at the top of your lungs, “I was adopted! Nooooooo.”"},
{'id': '97','que':"Text a friend and tell them their hair is on backward."},
{'id': '98','que':"Wear your clothes backward for the duration of the game."},
{'id': '99','que':"Tell someone something negative you have said about them in private."},
{'id': '100','que':"Go outside to the trash bin and throw a tantrum because someone put trash in it."},
{'id': '101','que':"Go outside and pick exactly 40 blades of grass with a pair of tweezers."},
{'id': '102','que':"Call someone and confess your new-found love for Justin Bieber."},
{'id': '103','que':"Kiss the person to your right on the cheek."},
{'id': '104','que':"Sniff the person to your left and tell them they smell bad."},
{'id': '105','que':"Rub your armpits and then smell your fingers."},
{'id': '106','que':"Sit on your hands for the remainder of the game."},
{'id': '107','que':"Knock on the neighbor’s door and ask if you can park your helicopter in their driveway."},
{'id': '108','que':"Take someone with you outside in the sight of the neighbors and stare into the sky until someone asks you what you are looking at, then tell them that you saw a UFO."},
{'id': '109','que':"Text your mom and tell her that you are expecting a baby."},
{'id': '110','que':"Walk outside frantically carrying an empty leash and approach people asking them if they have seen your pet alligator because it just escaped."},
{'id': '111','que':"Go into the bathroom and look in the cabinet. Write a short summary of what you find and read it to the group."},
{'id': '112','que':"Call the nearest gas station and ask them if they sell hemorrhoid cream."},
{'id': '113','que':"Stop a car that is going down the street and tell them that their wheels are turning."},
{'id': '114','que':"Make a sandwich containing every condiment in your refrigerator."},
{'id': '115','que':"Close your eyes and let everyone draw on you for 5 minutes."},
{'id': '116','que':"Tell a bizarre 2-minute story about the night you slept in the woods."},
{'id': '117','que':"Stand up and dance the twist until your next turn."},
{'id': '118','que':"Name the person in the room who you think is the best dressed."},
{'id': '119','que':"Name the person in the room who you think is the worst dressed."},
{'id': '120','que':"Text your siblings and tell them that you just found out you are adopted."},
{'id': '121','que':"Make the sound of a dripping faucet until your next turn."},
{'id': '122','que':"From now until the end of the game, every time you talk, speak like a robot."},
{'id': '123','que':"Act like a cheerleader and do a cheer about the host of the party."},
{'id': '124','que':"For the rest of the game, you must only communicate using animal sounds."},
{'id': '125','que':"Make confetti out of a tissue."},
{'id': '126','que':"Describe to the group what your last bathroom experience was like."},
{'id': '127','que':"Get a magazine and go outside. Roll up the magazine, put it on your nose and act and sound like an elephant."},
{'id': '128','que':"Make a hat out of aluminum foil then put the hat on and post a selfie to social media. Leave the hat on for the duration of the game."},
{'id': '129','que':"Hang your socks from your ears until the end of the game."},
{'id': '130','que':"Fill your mouth with water and act like a fountain."},
{'id': '131','que':"For the rest of the game you must say your name at the beginning and the end of every sentence you speak."},
{'id': '132','que':"Repeat everything the person to your left says until your next turn."},
{'id': '133','que':"Choose one inanimate object that is in the room. Now spend the next 2-minutes telling the group what that object is thinking."},
{'id': '134','que':"Attempt to lick your elbow for at least five minutes."},
{'id': '135','que':"Make eye contact with a player and don’t break it until it’s your turn again."},
{'id': '136','que':"Get a mouthful of water and gargle it until your next turn."},
{'id': '137','que':"Do the chicken dance to no music until your next turn."},
{'id': '138','que':"Crack an egg on your head."},
{'id': '139','que':"Stick out your tongue and talk that way until your next turn."},
{'id': '140','que':"Bust your best dance move right now."},
{'id': '141','que':"Turn your pants inside out and wear them."},
{'id': '142','que':"Do everything with “crab hands” for the rest of the game."},
{'id': '143','que':"Reenact what you think it is like to give birth."},
{'id': '144','que':"For the rest of the game, speak like you are the President of America."},
{'id': '145','que':"Pretend like you are drunk for the rest of the game."},
{'id': '146','que':"Eat a spoonful of hot sauce."},
{'id': '147','que':"Make up a short cheer and shout it to the room."},
{'id': '148','que':"Speak in the voice of your favorite cartoon character until your next turn."},
{'id': '149','que':"Use ketchup to put the mark of Simba on your forehead."},
{'id': '150','que':"Put a piece of American cheese on your cheek and leave it until your next turn."},

];