


final truth=  const [
  // {
  //   'id':'1',
  //   'que': 'what is your name?'
  // },
  //   {
  //   'id':'2',
  //   'que': 'where do you live?'
  // },
  //   {
  //   'id':'3',
  //   'que': 'who is your crush?'
  // },
  //   {
  //   'id':'4',
  //   'que': 'i am a joke to you?'
  // },
  //   {
  //   'id':'5',
  //   'que': 'who is joker?'
  // },
  // {'id': '6',
  // 'que':'What was the last thing you searched for on your phone?'
  // },
{'id': '1','que':'What was the last thing you searched for on your phone?'},
{'id': '2','que':'If you had to choose between going naked or having your thoughts appear in thought bubbles above your head for everyone to read, which would you choose?'},
{'id': '3','que':'Have you ever walked in on your parents doing it?'},
{'id': '4','que':'Have you ever walked in on your parents doing it?'},
{'id': '5','que':'Have you ever tasted a booger?'},
{'id': '6','que':'Have you ever played Cards Against Humanity with your parents?'},
{'id': '7','que':'What is the first thing you would do if you woke up one day as the opposite sex?'},
{'id': '8','que':'Have you ever peed in the pool?'},
{'id': '9','que':'Who do you think is the worst dressed person in this room?'},
{'id': '10','que':'Have you ever farted in an elevator?'},
{'id': '11','que':'True or false? You have a crush on [fill in the blank].'},
{'id': '12','que':'Of the people in this room, who do you want to trade lives with?'},
{'id': '13','que':'What are some things you think about when sitting on the toilet?'},
{'id': '14','que':'Did you have an imaginary friend growing up?'},
{'id': '15','que':'Do you cover your eyes during a scary part in a movie?'},
{'id': '16','que':'Have you ever practiced kissing in a mirror?'},
{'id': '17','que':'Did your parents ever give you the �birds and the bees� talk?'},
{'id': '18','que':'What is your guilty pleasure?'},
{'id': '19','que':'What is your worst habit?'},
{'id': '20','que':'Has anyone ever walked in on you when going #2 in the bathroom?'},
{'id': '21','que':'Have you ever had a wardrobe malfunction?'},
{'id': '22','que':'Have you ever walked into a wall?'},
{'id': '23','que':'Do you pick your nose?'},
{'id': '24','que':'Do you sing in the shower?'},
{'id': '25','que':'Have you ever peed yourself?'},
{'id': '26','que':'What was your most embarrassing moment in public?'},
{'id': '27','que':'Have you ever farted loudly in class?'},
{'id': '28','que':'Do you ever talk to yourself in the mirror?'},
{'id': '29','que':'You are in a public restroom and just went #2, then you realized your stall has no toilet paper. What do you do?'},
{'id': '30','que':'What would be in your web history that you would be embarrassed if someone saw?'},
{'id': '31','que':'Have you ever tried to take a sexy picture of yourself?'},
{'id': '32','que':'Do you sleep with a stuffed animal?'},
{'id': '33','que':'Do you drool in your sleep?'},
{'id': '34','que':'Do you talk in your sleep?'},
{'id': '35','que':'Who is your secret crush?'},
{'id': '36','que':'Do you think [fill in the name] is cute?'},
{'id': '37','que':'Who do you like the least in this room, and why?'},
{'id': '38','que':'What does your dream boy or girl look like?'},
{'id': '39','que':'What is your go-to song for the shower?'},
{'id': '40','que':'Who is the sexiest person in this room?'},
{'id': '41','que':'How would you rate your looks on a scale of 1 to 10?'},
{'id': '42','que':'Would you rather have sex with [insert name] in secret or not have sex with that person, but everyone thinks you did?'},
{'id': '43','que':"What don't you like about me?"},
{'id': '44','que':'What color underwear are you wearing right now?'},
{'id': '45','que':'What was the last thing you texted?'},
{'id': '46','que':'If you were rescuing people from a burning building and you had to leave one person behind from this room, who would it be?'},
{'id': '47','que':"Do you think you'll marry your current girlfriend/boyfriend?"},
{'id': '48','que':'How often do you wash your undergarments?'},
{'id': '49','que':'Have you ever tasted ear wax?'},
{'id': '50','que':'Have you ever farted and then blamed someone else?'},
{'id': '51','que':'Have you ever tasted your sweat?'},
{'id': '52','que':'What is the most illegal thing you have ever done?'},
{'id': '53','que':'Who is your favorite? Mom or Dad?'},
{'id': '54','que':'Would you trade your sibling in for a million dollars?'},
{'id': '55','que':'Would you trade in your dog for a million dollars?'},
{'id': '56','que':'What is your biggest pet peeve?'},
{'id': '57','que':'If you were allowed to marry more than one person, would you? Who would you choose to marry?'},
{'id': '58','que':'Would you rather lose your sex organs forever or gain 200 pounds?'},
{'id': '59','que':'Would you choose to save 100 people without anyone knowing about it or not save them but have everyone praise you for it?'},
{'id': '60','que':'If you could only hear one song for the rest of your life, what would it be?'},
{'id': '61','que':'If you lost one day of your life every time you said a swear word, would you try not to do it?'},
{'id': '62','que':'Who in this room would be the worst person to date? Why?'},
{'id': '63','que':'Would you rather live with no internet or no A/C or heating?'},
{'id': '64','que':'If someone offered you 1 million dollars to break up with your girlfriend/boyfriend, would you do it?'},
{'id': '65','que':'If you were reborn, what decade would you want to be born in?'},
{'id': '66','que':'If you could go back in time in erase one thing you said or did, what would it be?'},
{'id': '67','que':'Has your boyfriend or girlfriend ever embarrassed you?'},
{'id': '68','que':'Have you ever thought about cheating on your partner?'},
{'id': '69','que':'If you could suddenly become invisible, what would you do?'},
{'id': '70','que':'Have you ever been caught checking someone out?'},
{'id': '71','que':"Have you ever waved at someone thinking they saw you when really they didn't?What did you do when you realized it?"},
{'id': '72','que':"What's the longest time you've stayed in the bathroom, and why did you stay for that long?"},
{'id': '73','que':"What's the most unflattering school picture of you?"},
{'id': '74','que':'Have you ever cried because you missed your parents so much?'},
{'id': '75','que':'Would you rather be caught picking your nose or picking a wedgie?'},
{'id': '76','que':"Describe the strangest dream you've ever had. Did you like it?"},
{'id': '77','que':'Have you ever posted something on social media that you regret?'},
{'id': '78','que':'What is your biggest fear?'},
{'id': '79','que':'Do you pee in the shower?'},
{'id': '80','que':'Have you ever ding dong ditched someone?'},
{'id': '81','que':"The world ends next week, and you can do anything you want (even if it's illegal). What would you do?"},
{'id': '82','que':"Would you wear your shirt inside out for a whole day if someone paid you 100?"},
{'id': '83','que':'What is the most childish thing that you still do?'},
{'id': '84','que':'How far would you go to land the guy or girl of your dreams?'},
{'id': '85','que':'Tell us about a time you embarrassed yourself in front of a crush.'},
{'id': '86','que':'Have you ever kept a library book?'},
{'id': '87','que':"Who is one person you pretend to like, but actually don't?"},
{'id': '88','que':"What children's movie could you watch over and over again?"},
{'id': '89','que':'Do you have bad foot odor?'},
{'id': '90','que':'Do you have any silly nicknames?'},
{'id': '91','que':'When was the last time you wet the bed?'},
{'id': '92','que':'How many pancakes have you eaten in a single sitting?'},
{'id': '93','que':'Have you ever accidentally hit something with your car?'},
{'id': '94','que':'If you had to make out with any Disney character, who would it be?'},
{'id': '95','que':"Have you ever watched a movie you knew you shouldn't?"},
{'id': '96','que':'Have you ever wanted to try LARP (Live Action Role-Play)?'},
{'id': '97','que':'What app on your phone do you waste the most time on?'},
{'id': '98','que':'Have you ever pretended to be sick to get out of something? If so, what was it?'},
{'id': '99','que':'What is the most food you have eaten in a single sitting?'},
{'id': '100','que':'Do you dance when you are by yourself?'},
{'id': '101','que':'Would you have voted for or against Trump?'},
{'id': '102','que':'What song on the radio do you sing with every time it comes on?'},
{'id': '103','que':'Do you sleep with a stuffed animal?'},
{'id': '104','que':'Do you own a pair of footie pajamas?'},
{'id': '105','que':'Are you scared of the dark?'},
{'id': '106','que':'What As seen on TV product do you secretly want to buy?'},
{'id': '107','que':'Do you still take bubble baths?'},
{'id': '108','que':'If you were home by yourself all day, what would you do?'},
{'id': '109','que':'How many selfies do you take a day?'},
{'id': '110','que':'What is something you have done to try to be cooler?'},
{'id': '111','que':'When was the last time you brushed your teeth?'},
{'id': '112','que':'Have you ever used self-tanner?'},
{'id': '113','que':'What do your favorite pajamas look like?'},
{'id': '114','que':'Do you have a security blanket?'},
{'id': '115','que':'Have you ever eaten something off the floor?'},
{'id': '116','que':'Have you ever butt-dialed someone?'},
{'id': '117','que':'Do you like hanging out with your parents?'},
{'id': '118','que':'Have you ever got caught doing something you should not?'},
{'id': '119','que':'What part of your body do you love, and which part do you hate?'},
{'id': '120','que':'Have you ever had lice?'},
{'id': '121','que':'Have you ever pooped your pants?'},
{'id': '122','que':'What was the last R-rated movie you watched?'},
{'id': '123','que':'Do you lick your plate?'},
{'id': '124','que':'What is something that no one else knows about you?'},
{'id': '125','que':'Do you write in a diary?'},

];